### ISSUE TITLE
[BUG] kubedl manager startup fails

### ISSUE THREAD

**Issue by jian-he** [kubedl-io/kubedl#140]
**What happened**:
kubedl manager startup fails like below 

I0723 23:28:46.174606       1 controllers.go:42] workload Inference controller has started.
2021-07-23T23:28:46.174Z	INFO	setup	setting up storage backends
F0723 23:28:46.174685       1 client.go:32] get clientMgr fail, clientMgr is nil

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- KubeDL version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by SimonCqk** [comment]
fixed by #135
