### ISSUE TITLE
[BUG] create inference faiils 

### ISSUE THREAD

**Issue by jian-he** [kubedl-io/kubedl#141]
**What happened**:

I0724 02:15:02.997980       1 inference_controller.go:105] reconcile for inference instance: default/inference-aaa, status: &{ []}
E0724 02:15:03.000262       1 inference_controller.go:109] failed to sync service for inference, err: Service "inference-aaa" is invalid: spec.clusterIP: Invalid value: "": field is immutable
2021-07-24T02:15:03.000Z	ERROR	controller	Reconciler error	{"controller": "InferenceController", "name": "inference-aaa", "namespace": "default", "error": "Service \"inference-aaa\" is invalid: spec.clusterIP: Invalid value: \"\": field is immutable"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.4.1-0.20210423233217-9f3e0b1ce51b/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:246
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.20.7/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.7/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.7/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.20.7/pkg/util/wait/wait.go:90

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- KubeDL version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by SimonCqk** [comment]
fixed by pull request #143
