### ISSUE TITLE
[feature request] Add volcano scheduler as a new GangScheduler

### ISSUE THREAD

**Issue by HeGaoYuan** [kubedl-io/kubedl#150]
**What would you like to be added**:
I find that KubeDL now has two GangScheduler, kube-batch and kube-coscheduler, but miss the volcano scheduler. I want to add volcano scheduler as a new GangScheduler.

**Why is this needed**:
volcano scheduler is a popular gang scheduler, many users use it

**Comment by HeGaoYuan** [comment]
If you think it is reasonable, I can achieve it.

**Comment by SimonCqk** [comment]
hi @HeGaoYuan , the volcano gang api is derived from kube-batch, however, with the iteration of volcano project the api starts to appear different, it is welcomed if you can add volcano gang scheduler implementation!

**Comment by HeGaoYuan** [comment]
@SimonCqk Thanks for your reply. I will try it.

**Comment by SimonCqk** [comment]
@HeGaoYuan would you let us know which company do you work for  ?
