### ISSUE TITLE
[summer of code] integrate dataset cache with fluid

### ISSUE THREAD

**Issue by SimonCqk** [kubedl-io/kubedl#159]
## Topic Description

many DL workloads tend to accelerate on high-performance hardware in distributed training environments,  and with the dataset explosion, `I/O` becomes bottleneck of the entire system, [fluid](https://github.com/fluid-cloudnative/fluid) provides distributed cache facilities to improve the distributed training efficiency and we'd explore how to ingrate with it , including easy-to-use APIs and code implementation.

## Assignee

TODO

**Comment by zjchenn** [comment]
> ## Topic Description
> many DL workloads tend to accelerate on high-performance hardware in distributed training environments, and with the dataset explosion, `I/O` becomes bottleneck of the entire system, [fluid](https://github.com/fluid-cloudnative/fluid) provides distributed cache facilities to improve the distributed training efficiency and we'd explore how to ingrate with it , including easy-to-use APIs and code implementation.
> 
> ## Assignee
> TODO

Please assign to zjchenn. Thank you!
