### ISSUE TITLE
[BUG] mpi-operator has problems about DAG scheduling

### ISSUE THREAD

**Issue by HeGaoYuan** [kubedl-io/kubedl#164]
**What happened**: mpi job cannot work, the worker pod is blocking cause the configmap miss

**What you expected to happen**: mpi job works successful

**How to reproduce it**: run a mpi example with launcher and worker 

**Environment**:
- KubeDL version: master branch, latest commit

**Anything else we need to know?**:

First, there is a bug in the following code.

https://github.com/kubedl-io/kubedl/blob/6eb94727ef485f143e04fc94f5ce31d92b8796b5/apis/training/v1alpha1/mpijob_default.go#L70-L81

```golang
job.Spec.MPIReplicaSpecs[MPIReplicaTypeLauncher].DependOn = []v1.DAGCondition{
			{Upstream: MPIReplicaTypeLauncher, OnPhase: corev1.PodRunning},
		}
```

should be changed to 

```golang
job.Spec.MPIReplicaSpecs[MPIReplicaTypeLauncher].DependOn = []v1.DAGCondition{
			{Upstream: MPIReplicaTypeWorker, OnPhase: corev1.PodRunning},
		}
```

Second, even though fix the bug above. But the worker pod replies the configmap which create by following code. But because the dag scheduling enable, the logic will not reach here.

https://github.com/kubedl-io/kubedl/blob/6eb94727ef485f143e04fc94f5ce31d92b8796b5/controllers/mpi/pod.go#L60-L66

So, my opinion is disable/delete the dag scheduling in mpi job. The related discuss is here. https://github.com/kubedl-io/kubedl/issues/82#issuecomment-884229276

Looking forward to your reply.

**Comment by SimonCqk** [comment]
@HeGaoYuan thanks for your issue!
actually there comes 2 bugs in your content, both self-dependency and  job-config creation position will cause MPIJob in abnormal behaviours, I will fix them ASAP.
