### ISSUE TITLE
kubedl-dashboard Failed to watch *v1.Node: unknown (get nodes)

### ISSUE THREAD

**Issue by weini1** [kubedl-io/kubedl#173]
hello,
kubedl-dashboard is runing 
 kubectl get pod,svc -A
NAMESPACE       NAME                                          READY   STATUS              RESTARTS   AGE
default         pod/tf-distributed-worker-0                   0/1     Completed           0          4d23h
default         pod/tf-distributed-worker-1                   0/1     Completed           0          4d23h
default         pod/tf-distributed-worker-2                   0/1     Completed           0          4d23h
kubedl-system   pod/kubedl-7f4c55dfc9-gb5dz                   1/1     Running             1          6d6h
kubedl-system   pod/kubedl-dashboard-787b49c8d7-82926         1/1     Running             1          5d23h
NAMESPACE       NAME                               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
default         service/kubernetes                 ClusterIP   10.96.0.1        <none>        443/TCP                  6d6h
default         service/tf-distributed-worker-0    ClusterIP   None             <none>        2222/TCP                 4d23h
default         service/tf-distributed-worker-1    ClusterIP   None             <none>        2222/TCP                 4d23h
default         service/tf-distributed-worker-2    ClusterIP   None             <none>        2222/TCP                 4d23h
kube-system     service/kube-dns                   ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP   6d6h
kubedl-system   service/kubedl-dashboard-service   NodePort    10.110.120.255   <none>        9090:30001/TCP           5d23h
但是界面
CPU（核数）：0 / 0
内存（GB）：0 / 0
节点信息也是没有的，只有任务列表有完成的任务
kubedl-dashboard logs:
E0831 20:21:06.727197       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Node: unknown (get nodes)
E0831 20:21:47.874247       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Node: unknown (get nodes)
E0831 20:21:48.000941       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Namespace: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:kubedl-system:default" cannot list resource "namespaces" in API group "" at the cluster scope
E0831 20:22:44.186244       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Node: unknown (get nodes)
E0831 20:22:47.739211       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Namespace: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:kubedl-system:default" cannot list resource "namespaces" in API group "" at the cluster scope
E0831 20:23:23.703862       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Node: unknown (get nodes)
E0831 20:23:30.145446       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Namespace: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:kubedl-system:default" cannot list resource "namespaces" in API group "" at the cluster scope
E0831 20:24:07.173045       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Node: unknown (get nodes)
请问我哪里的配置没有配吗？

**Environment**:
- KubeDL version:v0.4.0
- Kubernetes version (use `kubectl version`):1.16.3
- OS (e.g: `cat /etc/os-release`):18.04.4 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`):Linux mnode 4.15.0-76-generic #86-Ubuntu SMP
- Install tools:yaml
- Others:

**Comment by jian-he** [comment]
@weini1 你好,
如这里所示：kubedl-system namespace下面的 default serviceaccount 需要添加 watch 和 list node权限 
可以通过kubectl describe serviceaccount -n kubedl-system 看一下他对应的clusterrole是哪个，
然后到clusterrole中添加 node 的 watch 和list权限，如 [这里](https://github.com/kubedl-io/kubedl/blob/716c1a5b235c84c5533e1a80badade1d631a1801/config/manager/all_in_one.yaml#L47-L53) 
 
```
E0831 20:22:47.739211 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1.Namespace: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:kubedl-system:default" cannot list resource "namespaces" in API group "" at the cluster scope
```

**Comment by weini1** [comment]
ok,thank you !

**Comment by shuxp** [comment]
我也遇到了这个问题，我用的都是默认的配置，这块不是很熟，能详细说明下吗？谢谢。

**Comment by shuxp** [comment]
尝试出来了，做一个clusterrolebinding就好
```
kubectl create clusterrolebinding xp-rb --clusterrole=cluster-admin --serviceaccount=kubedl-system:default
```
