### ISSUE TITLE
[feature request] debug异常，普通方法安装

### ISSUE THREAD

**Issue by githublaohu** [kubedl-io/kubedl#174]
**What would you like to be added**:
1. debug异常（其他项目启动没有）
操作系统：ubuntu18
go version go1.16.5 linux/amd64
编辑器为：vscode
vscode配置为
`
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}/console/backend/cmd/backend-server/main.go",
        }
    ]
}
`

`
Starting:/go/bin/dlv-dap dap --listen=127.0.0.1:39519 --log-dest=3 from /go/kubedl/.vscode/console/backend/cmd/backend-server
Error: Error: spawn /go/bin/dlv-dap ENOENT
dlv dap (undefined) exited with code: -2
Delve DAP server (PID: undefined) is not responding
`
2. 普通安装方式
k8s实在太重了，想从普通安装方式了解kubedl。

3. 请问配置说明在哪里
`
root@root:/kubedl$ ./backend-server 
F0907 15:35:25.740993    9583 client.go:35] could not create RESTMapper from config
`

4. 项目有多个main.go。可以说明下每个作用吗？

非常抱歉，也非常感谢。语言天赋实在太差了，英语阅读不行。
**Why is this needed**:

**Comment by SimonCqk** [comment]
@githublaohu hi，项目中应该只有两个main，一个是kubedl控制器本身的，一个是dashboard的，你第`3`点尝试启动的是backend-server；
报错是没有解析到正确的kubeconfig，通过`KUBECONFIG`环境变量指定好对应的k8s集群路径，或者`--kubeconfig`启动参数指定路径 :）

**Comment by SimonCqk** [comment]
btw，如果想单独启动dashboard backend，可以参考dashboard的Dockerfile

https://github.com/kubedl-io/kubedl/blob/master/Dockerfile.dashboard

**Comment by githublaohu** [comment]
非常感谢，目前已经debug backend-server了。
非常抱歉，找不到配置文件的配置内容，config目录是yaml看了下基本是k8s的。想知道需要那些配置。
                      根目录下的main.go也需要配置文件，但是也不知道需要配置那些内容。
backend-server 是 dashboard吗？
那根目录下main.go就是kubedl控制本身了吧。

**Comment by githublaohu** [comment]
@SimonCqk  大佬，上午好。打扰了。
麻烦，解答下问题好吗？
kubedl的文档实在太少了。百度与google基本无任何结果。

**Comment by jian-he** [comment]
@githublaohu 你好，这里有 dashboard的文档，https://kubedl.io/docs/recipes/dashboard/#run-backend-server-locally

backend-server是dashboard的后端服务
根目录下的main.go是 Kubedl controller的main

**Comment by githublaohu** [comment]
大佬你好，在百忙之中打扰了，对kubedl有些地方不理解。

1. 控制台与kubedl的启动配置说明在哪里。
    1. 看了控制台的main.go与client.go ，只需要rest-client的配置
    2. 主目录下的main.go 做了很多操作。比如读取apis, scheme, schedulers等等还需要深读。
2. 请问GPU的识别调度的源码在那个文件。

kubedl的源码看了下，还是比较简单的。是connect-runtime这个框架，等下去研究。


官网列出KubeDL与oschina不同。领导是一个追求细节的算法工程师，必须了解kubeDL所有特性，要不很难说服他。

我是做工程的,主攻java，存储，中间件。不是做算法的，一些名词不是很理解。麻烦大佬解读下

官网上列了kubeDL的特点
1. 支持多个深度学习框架
2. 有模型与模板版本管理
3. 定时调度训练
4. 支持云

在oschina是这样表述的

其核心功能包括：
1. 在将 ML 模型部署为推理服务之前自动调整最佳容器级配置。- Morphling Github
      是否可以这样理解：基于模型信息，分析出来需要的资源配置（存储，cpu）构建一个容器，然后在容器上启动推理服务，加载模型。
2. 用于在 CRD 中本地跟踪模型历史的模型沿袭和版本控制：何时使用哪些数据和哪些图像训练模型、模型的每个版本、正在运行的版本等。
          理解为：有个模型管理模块
3. 启用利用容器映像存储和版本控制模型。每个模型版本都存储为自己的图像，以后可以使用 Serving 框架提供服务。
          理解为：每个模型版本都有一个容器。不理解什么是Serving 框架提供服务
4. 在单个统一控制器中支持推理框架和训练工作负载（Tensorflow、Pytorch、Mars等）。

总结
1. 模板管理
2. 深度学习与集群学习框架依赖
3. k8s管理，调度以及统计分析
4. 推理服务构建

上个月看官网的时候，说支持GPU吗？ 很想了解这个能力。

**Comment by githublaohu** [comment]
controller-runtime 框架支持服务内选举。很优秀，在kubedl里面没有看到相关配置。尤其是普通方法安装的配置。 @jian-he

**Comment by SimonCqk** [comment]
@githublaohu 选举相关的config，在main.go中都可以看到，主要通过--enable-leader-election=true|false来enable，其余的我们用了默认的配置，如果希望有更详细的config设置入口，可以给我们提issue :)

**Comment by githublaohu** [comment]
@SimonCqk   在mian.go看到了。但是节点是怎么配置，不知道。

大佬，可以介绍下kubeDL，如何支持GPU的吗？

**Comment by jian-he** [comment]
@githublaohu GPU支持只需要在spec 里面填写 相应的GPU request 
https://github.com/kubedl-io/kubedl/blob/b40c66897da04849c358aa1f043747979ffe0889/pkg/job_controller/api/v1/types.go#L83

你说的节点是怎么配置是什么意思

**Comment by githublaohu** [comment]
目前已经可以debug启动了，启动后需要读取配置参数，没有参数直接报错。目前不清楚仪表盘与控制服务需要那些配置。

**Comment by githublaohu** [comment]
目前已经可以debug启动了，启动后需要读取配置参数，没有参数直接报错。目前不清楚仪表盘与控制服务需要那些配置。
