### ISSUE TITLE
钉钉的二维码过期了。该怎么加入群

### ISSUE THREAD

**Issue by wangjxian** [kubedl-io/kubedl#175]
钉钉的二维码过期了。该怎么加入群

**Comment by jian-he** [comment]
@wangjxian 你好可以用这个链接加入  https://h5.dingtalk.com/circle/healthCheckin.html?dtaction=os&corpId=ding66e5c6edd2286ee0daaacaebab5406a2&b2324693-=bf33ff07-&cbdbhh=qwertyuiop

或者二维码
![Xnip2021-09-08_15-05-30](https://user-images.githubusercontent.com/3662775/132592005-a06b5eaf-e75a-42e0-9e73-0ccd4c060a3b.jpg)
