### ISSUE TITLE
[feature request] 想要详细的config设置入口

### ISSUE THREAD

**Issue by githublaohu** [kubedl-io/kubedl#176]
**What would you like to be added**:
想要详细的config设置入口。这样可以自己定义kebedl集群

**Why is this needed**:
开发与运维需要

**Comment by SimonCqk** [comment]
https://github.com/kubedl-io/kubedl/blob/master/docs/startup_flags.md
这里包含了部分启动参数，需要哪些更详细的config，可以直接在issue上罗列，我们会支持 :)
