### ISSUE TITLE
[BUG]dashboard无法识别GPU

### ISSUE THREAD

**Issue by CaRRotOne** [kubedl-io/kubedl#185]
**What happened**:
dashboard无法识别GPU，GPU为 nvidia显卡， K8S已经安装对应nvidia插件

**What you expected to happen**:
解决dashboard GPU显示问题

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- KubeDL version: lastest
- Kubernetes version (use `kubectl version`): v1.17.17
- OS (e.g: `cat /etc/os-release`): ubuntu
- Kernel (e.g. `uname -a`): 
- Install tools:
- Others:
![image](https://user-images.githubusercontent.com/2860023/134864344-517b4547-e2a3-43d8-af62-8dd2e75fe12d.png)

**Comment by SimonCqk** [comment]
@CaRRotOne 好的，我们看下

麻烦提供一下集群的node信息，nvidia插件是否有正常工作，以及node allocatable资源上报是否符合预期

**Comment by CaRRotOne** [comment]
> @CaRRotOne 好的，我们看下
> 
> 麻烦提供一下集群的node信息，nvidia插件是否有正常工作，以及node allocatable资源上报是否符合预期

@SimonCqk 
集群为rancher搭建的k8s，具体信息图下。请教一下，node allocatable资源上报具体应该如何查看？

```
kubectl cluster-info
Kubernetes master is running at https://ml.rancher.pudu.cn:9443/k8s/clusters/c-tzdlr
CoreDNS is running at https://ml.rancher.pudu.cn:9443/k8s/clusters/c-tzdlr/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```
```
kubectl get nodes
NAME                  STATUS   ROLES                      AGE     VERSION
dell-poweredge-t640   Ready    controlplane,etcd,worker   2d23h   v1.17.17
```
nvidia插件已正常工作
```
kubectl get pods -n kube-system | grep nvidia
nvidia-device-plugin-daemonset-sfckg      1/1     Running     0          41m
```

**Comment by CaRRotOne** [comment]
已解决，docker的default-runtime需要设置成nvidia

**Comment by SimonCqk** [comment]
> 已解决，docker的default-runtime需要设置成nvidia

感谢关注，那我关闭这个issue啦  :)

**Comment by CaRRotOne** [comment]
@SimonCqk 好的，感谢，持续关注kubedl，愿产品越来越好！
