### ISSUE TITLE
[BUG] dashboard don't show the task logs

### ISSUE THREAD

**Issue by CaRRotOne** [kubedl-io/kubedl#210]
**What happened**:
I run example jobs([tf_job_mnist.yaml](https://github.com/kubedl-io/kubedl/blob/master/example/tf/tf_job_mnist.yaml))，dashboard don't show the logs, user logs is blank, and system logs only show little information.  I check the pod logs, it's completed.

user logs:
![image](https://user-images.githubusercontent.com/2860023/143400369-01d6c252-9fcd-4274-bf9f-99ef27220d62.png)
system logs:
![image](https://user-images.githubusercontent.com/2860023/143400442-1d1fe33b-b232-4451-8d64-fdd29740a8a4.png)
pod logs:
![image](https://user-images.githubusercontent.com/2860023/143401407-fa73e0f2-2115-46bd-b156-fa5f0a7c3ad9.png)

**What you expected to happen**:
show the pod's logs on the dashboard.

**How to reproduce it**:
submit jobs using 'kubectl apply -f tf_job_mnist.yaml'

**Anything else we need to know?**:

**Environment**:
- KubeDL version: latest
- Kubernetes version (use `kubectl version`): 1.20
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by SimonCqk** [comment]
@CaRRotOne hi, did you click `User Logs`  a not-short period after pod completed? Dashboard retrieves pod logs from apiserver and it will no longer exists once rootfs of container was reclaimed.

**Comment by CaRRotOne** [comment]
> @CaRRotOne hi, did you click `User Logs` a not-short period after pod completed? Dashboard retrieves pod logs from apiserver and it will no longer exists once rootfs of container was reclaimed.

@SimonCqk  the User Logs doesn't show anything neither pod running nor pod completed.

**Comment by SimonCqk** [comment]
@CaRRotOne as we offline discussed, it is caused by `pods/log` rbac configuration and has been fixed.
