### ISSUE TITLE
if  jupyter(lab) will be added to kubedl?

### ISSUE THREAD

**Issue by shuxp** [kubedl-io/kubedl#224]
for dl, jupyter is widely used for ai project.
hope jupyter in kubedl.
Is it possible?

**Comment by SimonCqk** [comment]
hi @shuxp , the proto version of `notebook` implementation has checked in and you're welcomed to hands up!

see https://github.com/kubedl-io/kubedl/blob/master/apis/notebook/v1alpha1/notebook_types.go for details, we'll provide more documents later.

**Comment by shuxp** [comment]
it seems kubedl being developed rapidly over these days. When will it reach a relative stable state(normal functions developed)?

**Comment by jian-he** [comment]
Juypter Lab is added as one of the Notebook CRD type  https://github.com/kubedl-io/kubedl/blob/master/apis/notebook/v1alpha1/notebook_types.go
