### ISSUE TITLE
[feature request]mac m1 how to install kubedl

### ISSUE THREAD

**Issue by xiao-jay** [kubedl-io/kubedl#246]
when I want to exec ```helm install kubedl ./helm/kubedl --create-namespace -n kubedl-system```,
i get this error ```Error: INSTALLATION FAILED: path "./helm/kubedl" not found```

**What would you like to be added**:
I want to someson add doc of install kubedl in mac
**Why is this needed**:
Easy to quickstart locally

**Comment by xiao-jay** [comment]
when i runing ```kubectl apply -f https://raw.githubusercontent.com/kubedl-io/kubedl/master/example/tf/tf_job_mnist_distributed_simple.yaml```,
i got the error ```error: unable to recognize "tf_job_mnist_distributed_simple.yaml": no matches for kind "TFJob" in version "training.kubedl.io/v1alpha1"```

**Comment by jian-he** [comment]
> Error: INSTALLATION FAILED: path "./helm/kubedl" not found

Are you running from the project root  folder ?
@xiao-jay

**Comment by SimonCqk** [comment]
@xiao-jay hi jay, it seems platform agnostic base on the error message, please make sure execute `helm` commands from the root folder

**Comment by xiao-jay** [comment]
thank you jian-he and simonCqk ,i will try your Suggest

**Comment by xiao-jay** [comment]
oh,i know what is the root folder. I thought the root folder is ```cd  /``` and run  ```helm install kubedl ./helm/kubedl --create-namespace -n kubedl-system``` before.
But the correctly operate is ```git clone git@github.com:kubedl-io/kubedl.git ``` and  ```cd kubedl``` and run install command.
In the end,thanks @jian-he @SimonCqk
