### ISSUE TITLE
[BUG]make generate and make manifests commands do not work

### ISSUE THREAD

**Issue by jian-he** [kubedl-io/kubedl#256]
**What happened**:
make generate and make manifests commands do not work

**Environment**:
- KubeDL version: master branch

**Comment by SimonCqk** [comment]
please go get latest controller-gen command tools via `go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.6.1`

**Comment by jian-he** [comment]
You are right, I'll add this to the documentation
