### ISSUE TITLE
[feature request] Validate the helm chart is in sync in CI test

### ISSUE THREAD

**Issue by jian-he** [kubedl-io/kubedl#258]
**What would you like to be added**:
The helm chart is always missing to be updated, we could enforce this in CI test

**Why is this needed**:

**Comment by basit9958** [comment]
@jian-he Sir, I would like to work on this issue 
I propose ct which is the the tool for testing Helm charts. It is meant to be used for linting and testing pull requests. It automatically detects charts changed against the target branch. After linting we can use [hvral](https://github.com/stefanprodan/hrval-action#usage-with-pull-requests-containing-changes-of-helm-chart-source-located-in-base-repository-branch ) 
The action works by:
- Downloading the helm chart.
- Running a helm template using both the default values and also the values specified in the given HelmRelease.
