### ISSUE TITLE
[BUG]the Dingtalk link is error in the kubedl docs

### ISSUE THREAD

**Issue by d821776892** [kubedl-io/kubedl#273]
https://kubedl.io/docs/help
![image](https://user-images.githubusercontent.com/56722812/196997254-cdb54b7b-fec1-46b3-aeb7-6eb2b75e0efb.png)
[clicking this link](https://h5.dingtalk.com/circle/healthCheckin.html?dtaction=os&corpId=ding66e5c6edd2286ee0daaacaebab5406a2&b2324693-=bf33ff07-&cbdbhh=qwertyuiop) is error.

thanks

**Comment by SimonCqk** [comment]
@d821776892 hi, it seems dingtalk link has expired, I will refresh a new one.

**Comment by SimonCqk** [comment]
@d821776892 hi, the latest dingtalk QR code has been uploaded, please checkout
